version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres.dev.tiagodeliberali.com.br
    environment:
      POSTGRES_USER: "ecommerce"
      POSTGRES_PASSWORD: "letmein"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./.containers/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - private

volumes:
  postgres-volume:
    external: true

networks:
  private:
    external:
      name: private